version: '3.4'

services:
  api:
    build:
      context: .
      target: production #sirve para que frene en el primer FROM
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: npm run dev # sobreEscribe npm run build
